# Structuri de date in pandas

+ ## Series 
+ ##  Frames


---

## Series

Un obiect de tip Series = Obiect de tip 1D array conținând o secvență de valori și o serie de indecsi. 

Implicit indecsii sunt 0,1,…, size-1.


In [0]:
import pandas as pd
print(pd.__version__)

1.5.3


In [0]:
a = pd.Series([1, 2, 3, 4])

In [0]:
a

0    1
1    2
2    3
3    4
dtype: int64

In [0]:
print(a)

0    1
1    2
2    3
3    4
dtype: int64


In [0]:
type(a)

pandas.core.series.Series

In [0]:
a.values

array([1, 2, 3, 4])

In [0]:
a.index

RangeIndex(start=0, stop=4, step=1)

In [0]:
a.size

4

In [0]:
a.dtype

dtype('int64')

In [0]:
a[0]

1

In [0]:
a[0:3]

0    1
1    2
2    3
dtype: int64

Putem defini si alti indecsi.

In [0]:
b = pd.Series([2, 3, 7, 1, 0], index=['a', 'b', 'c', 'd', 'e'])
c = pd.Series([2, 4, 5], index = list('xyz'))

In [0]:
print(b)
print(c)

a    2
b    3
c    7
d    1
e    0
dtype: int64
x    2
y    4
z    5
dtype: int64


In [0]:
print(b)

print("\n")
print(c[-1])

print("\n")
print(b['a':'c'])

print("\n")
print(b[0:2])

a    2
b    3
c    7
d    1
e    0
dtype: int64


5


a    2
b    3
c    7
dtype: int64


a    2
b    3
dtype: int64


In [0]:
b.values

array([2, 3, 7, 1, 0])

In [0]:
b.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

Putem folosi indecsi pentru a accesa anumite elemente ale seriei.

In [0]:
a[1] = 10
a

0     1
1    10
2     3
3     4
dtype: int64

In [0]:
b['c']

7

Putem accesa doar o parte din elementele vectorului.

In [0]:
a[0:2] # accesam elementele cu indicii 0,1


0     1
1    10
dtype: int64

In [0]:
x = b['a':'d'] # observati diferenta. in pandas includem si elementul cu ultimul index - adica d

print(x)

type(x)

a    2
b    3
c    7
d    1
dtype: int64


pandas.core.series.Series

In [0]:
print(a[[0,2]])
b[['a', 'c']]

0    1
2    3
dtype: int64


a    2
c    7
dtype: int64

In [0]:
print(a[[0,3]]) # aici am precizat lista de indecsi

a[[2, 3]] = 5
print(a)

0    1
3    4
dtype: int64
0     1
1    10
2     5
3     5
dtype: int64


In [0]:
b[['d', 'c', 'e']] # aici am precizat lista de indecsi

d    1
c    7
e    0
dtype: int64

In [0]:
b

a    2
b    3
c    7
d    1
e    0
dtype: int64

Putem modifica valorile unei serii prin intermediul indecsilor.

In [0]:
b['c']=9

In [0]:
b

a    2
b    3
c    9
d    1
e    0
dtype: int64

In [0]:
b['b':'d'] = 100
b


a      2
b    100
c    100
d    100
e      0
dtype: int64

Putem aplica operatorii >, <, == unei serii asa cum putem face si in NumPy. Astfel putem accesa doar o parte din elementele seriei.

In [0]:
a > 2

0    False
1     True
2     True
3     True
dtype: bool

In [0]:
a[a > 2]

1    10
2     5
3     5
dtype: int64

In [0]:
c = a[ a > 2]
c

1    10
2     5
3     5
dtype: int64

In [0]:
c = pd.Series([2, 4, 5], index = list('xyz'))
print(c)
c.index

x    2
y    4
z    5
dtype: int64


Index(['x', 'y', 'z'], dtype='object')

---

## Ex. 1. 

+ Creati o serie s1 cu elementele 10, 15, 20, 25 si index default

In [0]:
s1 = pd.Series([10,15,20,25])
s1

0    10
1    15
2    20
3    25
dtype: int64

+ Creati o serie s2 cu elementele 'luni', 'marti','miercuri', 'joi', 'vineri' si indici 'L', 'Ma', 'Mi', 'J', 'V'

In [0]:
s2 = pd.Series(['luni','marti','miercuri','joi','vineri'], index=['L','Ma','Mi','J','v'])
s2

L         luni
Ma       marti
Mi    miercuri
J          joi
v       vineri
dtype: object

+ Aplicati index si values 

In [0]:
s2.index

Index(['L', 'Ma', 'Mi', 'J', 'v'], dtype='object')

In [0]:
s2.values

array(['luni', 'marti', 'miercuri', 'joi', 'vineri'], dtype=object)

Scrieti elementul cu valoarea 'marti'

In [0]:
s2[s2=='marti']

Ma    marti
dtype: object

---

In [0]:
import numpy as np
print (np.__version__)

1.23.5


In [0]:
a

0     1
1    10
2     5
3     5
dtype: int64

In [0]:
d = np.where(a > 2, a, -1)
d

array([-1, 10,  5,  5])

Putem forma o serie plecand de la un dictionar Python (dict)

In [0]:
inaltime = {'Ionel': 176, 'Mihai': 185, 'Maria': 170, 'Anda':160}
inaltime

{'Ionel': 176, 'Mihai': 185, 'Maria': 170, 'Anda': 160}

In [0]:
tabel_inaltime =  pd.Series(inaltime)

In [0]:
tabel_inaltime

Ionel    176
Mihai    185
Maria    170
Anda     160
dtype: int64

In [0]:
tabel_inaltime.index

Index(['Ionel', 'Mihai', 'Maria', 'Anda'], dtype='object')

In [0]:
tabel_inaltime.values

array([176, 185, 170, 160])

In [0]:
tabel_inaltime[['Ionel','Anda']]

Ionel    176
Anda     160
dtype: int64

Putem forma o serie plecand de la o parte din dictionar

In [0]:
tabel_inaltime2 = pd.Series(inaltime, index =['Maria', 'Ionel'])

In [0]:
tabel_inaltime2

Maria    170
Ionel    176
dtype: int64

In [0]:
tabel_inaltime3 = pd.Series(inaltime, index =['Maria', 'Ionel', 'Dorin', 'Vasile'])
tabel_inaltime3

Maria     170.0
Ionel     176.0
Dorin       NaN
Vasile      NaN
dtype: float64

Pentru etichetele (cheile) 'Dorin' si 'Vasile' nu au fost gasite valori, 
tabelul a fost completat cu NaN (not a number) care marcheaza **datele lipsa**.


Putem verifica daca o serie contine date lipsa apeland functiile pandas: **isnull** si **notnull** care vor returna valori booleene (True sau False).

In [0]:
pd.isnull(tabel_inaltime)
tabel_inaltime

Ionel    176
Mihai    185
Maria    170
Anda     160
dtype: int64

In [0]:
pd.isnull(tabel_inaltime2)
#tabel_inaltime2

Maria    False
Ionel    False
dtype: bool

In [0]:
pd.isnull(tabel_inaltime3)

Maria     False
Ionel     False
Dorin      True
Vasile     True
dtype: bool

In [0]:
pd.notnull(tabel_inaltime3)
 

Maria      True
Ionel      True
Dorin     False
Vasile    False
dtype: bool

In [0]:
pd.notnull(tabel_inaltime2)

Maria    True
Ionel    True
dtype: bool

sau folosim functia metoda **isnull** a obiectului de tip Series

In [0]:
tabel_inaltime3.isnull()

Maria     False
Ionel     False
Dorin      True
Vasile     True
dtype: bool

In [0]:
tabel_inaltime + tabel_inaltime2
#tabel_inaltime2

Anda       NaN
Ionel    352.0
Maria    340.0
Mihai      NaN
dtype: float64

In [0]:
# tabel_inaltime + tabel_inaltime2 + tabel_inaltime3 #desi seriile nu au aceeasi dimensiune, nu obtinem eroare
(tabel_inaltime + tabel_inaltime2) + tabel_inaltime3

Anda        NaN
Dorin       NaN
Ionel     528.0
Maria     510.0
Mihai       NaN
Vasile      NaN
dtype: float64

In [0]:
tabel_inaltime

Ionel    176
Mihai    185
Maria    170
Anda     160
dtype: int64

In [0]:
tabel_inaltime2

Maria    170
Ionel    176
dtype: int64

In [0]:
tabel_inaltime3

Maria     170.0
Ionel     176.0
Dorin       NaN
Vasile      NaN
dtype: float64

Observati cum a fost facuta adunarea celor 3 serii. Ordonarea se face alfabetic dupa cheile corespunzatoare valorilor adunate.

In [0]:
tabel_inaltime.name = 'Inaltime' 
tabel_inaltime

Ionel    176
Mihai    185
Maria    170
Anda     160
Name: Inaltime, dtype: int64

In [0]:
tabel_inaltime.index.name = 'Nume' 


In [0]:
tabel_inaltime

Nume
Ionel    176
Mihai    185
Maria    170
Anda     160
Name: Inaltime, dtype: int64

# DataFrame

Un dataframe reprezintă un tabel de date cu linii si coloane, fiecare dintre acestea putând fi de tipuri diferite (numeric, șir, boolean etc.) 
 


DataFrame are un index pentru rânduri și pentru coloane; poate fi gândit ca un dict de Series, toate avand același index.


Putem construi un Dataframe plecand de la un dictionar de liste  

In [0]:
data = {'Vant': ['T', 'F','T', 'T'], 'Temperatura': [15, 20, 7, 10], 'Umiditate': ['scazuta', 'normala', 'ridicata', 'normala']}

In [0]:
data

{'Vant': ['T', 'F', 'T', 'T'],
 'Temperatura': [15, 20, 7, 10],
 'Umiditate': ['scazuta', 'normala', 'ridicata', 'normala']}

In [0]:
df = pd.DataFrame(data)
df

,Vant,Temperatura,Umiditate
0,T,15,scazuta
1,F,20,normala
2,T,7,ridicata
3,T,10,normala


Putem preciza ordinea coloanelor. Putem adauga coloane noi. Cele fara valori apar cu NaN.

In [0]:
df2 = pd.DataFrame(data, columns =['Temperatura', 'Vant', 'Umiditate', 'Clasa'])
df3 = pd.DataFrame(data, columns =['Temperatura', 'Vant', 'Umiditate'])
df2

,Temperatura,Vant,Umiditate,Clasa
0,15,T,scazuta,NaN
1,20,F,normala,NaN
2,7,T,ridicata,NaN
3,10,T,normala,NaN


In [0]:
print(df2['Vant'])
type(df2['Vant'])

0    T
1    F
2    T
3    T
Name: Vant, dtype: object


pandas.core.series.Series

In [0]:
df2['Vant'][1] 


'F'

In [0]:
df2.dtypes

Temperatura     int64
Vant           object
Umiditate      object
Clasa          object
dtype: object

Putem construi un Dataframe plecand de la un dictionar ce contine si o serie.

In [0]:
d = {'Temperatura': [3, 10, 17, 10], 'Temp_noaptea': pd.Series([3, 8, 12], index = [0,2,3])}
#d = {'Temp_noaptea': pd.Series([3, 8, 12], index = [0,2,3])}
d
#df_1_2 = pd.DataFrame(d, index=range(4))
#df_1_2

{'Temperatura': [3, 10, 17, 10],
 'Temp_noaptea': 0     3
 2     8
 3    12
 dtype: int64}

In [0]:
df_3 = pd.DataFrame(d, index=range(4))
df_3

,Temperatura,Temp_noaptea
0,3,3.0
1,10,NaN
2,17,8.0
3,10,12.0


In [0]:
v = pd.Series([3, 8, 12], index = [0,2,3])

In [0]:
v

0     3
2     8
3    12
dtype: int64

In [0]:
d2 =  {'Temp_noaptea': v}

In [0]:
d2

{'Temp_noaptea': 0     3
 2     8
 3    12
 dtype: int64}

In [0]:
df_4 = pd.DataFrame(d2, index = [0,1,2,3])

In [0]:
df_4

,Temp_noaptea
0,3.0
1,NaN
2,8.0
3,12.0


---

## Ex. 2. 

+ Plecand de la un dictionar, creati un DataFrame care sa corespunda urmatorului tabel:

|   | Cantitate | Pret unitar | Cantitate maxima | Vandut | Pret total |
|---|-----------|-------------|------------------|--------|------------|
| 1 | 23        | 14.99       | 100              | False  | NaN        |
| 2 | 45        | 23.50       | 100              | False  | NaN        |
| 3 | 15        | 58.00       | 100              | False  | NaN        |
| 4 | 34        | 76.25       | 100              | False  | NaN        |


In [0]:
d = {'Cantitate': [23, 45, 15, 34], 'Pret unitar': [14.99, 23.50, 58.00, 76.25], 'Cantitate maxima': np.full(4,100), 'Vandut': np.full(4, False), 'Pret total': [np.nan, np.nan, np.nan, np.nan]}
print(d)

df2 = pd.DataFrame(d,index=range(4))
df2

{'Cantitate': [23, 45, 15, 34], 'Pret unitar': [14.99, 23.5, 58.0, 76.25], 'Cantitate maxima': array([100, 100, 100, 100]), 'Vandut': array([False, False, False, False]), 'Pret total': [nan, nan, nan, nan]}


,Cantitate,Pret unitar,Cantitate maxima,Vandut,Pret total
0,23,14.99,100,False,NaN
1,45,23.50,100,False,NaN
2,15,58.00,100,False,NaN
3,34,76.25,100,False,NaN


Putem construi un Dataframe plecand de la un sir de vectori Numpy

In [0]:
import numpy as np

In [0]:
t =  pd.DataFrame(np.array([[1,4,8,5], [5,3,2,1], [6,7,8,9]]), columns = list('xyzt'))

In [0]:
t

,x,y,z,t
0,1,4,8,5
1,5,3,2,1
2,6,7,8,9


In [0]:
t2 =  pd.DataFrame(np.array([[1, 2, 0, 5], [5,-3,2,1], [6,7,-8,9]]), columns = list('xyzt'),index = ['unu', 'doi', 'trei'])

In [0]:
t2


,x,y,z,t
unu,1,2,0,5
doi,5,-3,2,1
trei,6,7,-8,9


Selectare coloane

In [0]:
t2['x']  # coloana cu numele x
# sau 
t2.x  # daca numele coloanei are formatul de nume de variabila Python

unu     1
doi     5
trei    6
Name: x, dtype: int64

In [0]:
t2['x']= 6
t2

,x,y,z,t
unu,6,2,0,5
doi,6,-3,2,1
trei,6,7,-8,9


In [0]:
t2[ t2 > 0 ]


,x,y,z,t
unu,6,2.0,NaN,5
doi,6,NaN,2.0,1
trei,6,7.0,NaN,9


In [0]:
print(t2[t2['y'] > 1])
print(type(t2['x']))
print(t2)

      x  y  z  t
unu   6  2  0  5
trei  6  7 -8  9
<class 'pandas.core.series.Series'>
      x  y  z  t
unu   6  2  0  5
doi   6 -3  2  1
trei  6  7 -8  9


In [0]:
t2['t'] = t2['x'] + t2['y']  # putem modifica o coloana 
t2

,x,y,z,t
unu,6,2,0,8
doi,6,-3,2,3
trei,6,7,-8,13


---

## Ex. 3.

+ In DataFrame-ul creat la ex. 2, 

|   | Cantitate | Pret unitar | Pret total |
|---|-----------|-------------|------------|
| 1 | 23        | 14.99       | NaN        |
| 2 | 45        | 23.65       | NaN        |
| 3 | 15        | 59.00       | NaN        |
| 4 | 34        | 76.00       | NaN        |

modificati coloana **_Pret total_** astfel incat sa reprezinte pretul total al produselor achizitionate (**_Cantitate_** = nr de produse, **_Pret unitar_** = pretul fiecarui produs).

 

In [0]:
df2['Pret total'] = df2['Cantitate'] * df2['Pret unitar']
df2

,Cantitate,Pret unitar,Cantitate maxima,Vandut,Pret total
0,23,14.99,100,False,344.77
1,45,23.50,100,False,1057.50
2,15,58.00,100,False,870.00
3,34,76.25,100,False,2592.50


---

Selectare linii

In [0]:
print(t2.loc['unu']) # linia cu index 'unu' | label based
t2

x    6
y    2
z    0
t    8
Name: unu, dtype: int64


,x,y,z,t
unu,6,2,0,8
doi,6,-3,2,3
trei,6,7,-8,13


In [0]:
t2

,x,y,z,t
unu,6,2,0,8
doi,6,-3,2,3
trei,6,7,-8,13


In [0]:
t2.loc[['unu','doi']] 

,x,y,z,t
unu,6,2,0,8
doi,6,-3,2,3


In [0]:
t2.loc['unu':'trei'] # observati ca este inclusa si linia cu indexul 'trei'
# label-based slicing in pandas is inclusive.

,x,y,z,t
unu,6,2,0,8
doi,6,-3,2,3
trei,6,7,-8,13


In [0]:
t2.loc[['unu','doi'],'y']


unu    2
doi   -3
Name: y, dtype: int64

In [0]:
t2

,x,y,z,t
unu,6,2,0,8
doi,6,-3,2,3
trei,6,7,-8,13


In [0]:
t2.iloc[2] # linia cu indexul numeric 2 (de la 0 incepand numerotarea) | numerical indices based

x     6
y     7
z    -8
t    13
Name: trei, dtype: int64

In [0]:
t2.iloc[2,2] # elem de pe linia 2 col 2 (de la 0 incepand numerotarea)


-8

In [0]:
print(t2.iloc[0:3:2]) # from, to, step
t2

      x  y  z   t
unu   6  2  0   8
trei  6  7 -8  13


,x,y,z,t
unu,6,2,0,8
doi,6,-3,2,3
trei,6,7,-8,13


In [0]:
print(t2.iloc[:,0:5:2]) # x,y - row , column (0:5:2 step)
t2.dtypes

      x  z
unu   6  0
doi   6  2
trei  6 -8


x    int64
y    int64
z    int64
t    int64
dtype: object

---

## Ex.4.

+ Creati un DataFrame care sa corespunda urmatorului tabel: (pt valoarea NaN (not-a-number) puteti folosi *np.nan* sau *None*)

|         | Nota romana | Nota matematica |
|---------|-------------|-----------------|
| a       | 10.0        | 8.0             |
| b       | 8.0         | 10.0            |
| c       | NaN         | 7.0             |
| d       | 8.0         | 6.0             |
| e       | 9.0         | NaN             |


In [0]:
df_ex4_test = pd.DataFrame(np.array([[10.0,8.0,np.nan,8.0,9.0],[8.0,10.0,7.0,6.0,np.nan]]).T,columns=['Nota romana','Nota matematica'],index=['a','b','c','d','e']) # transpose (2,5) -> (5,2)

df_ex4 = pd.DataFrame({"Nota romana": [10.0, 8.0, np.nan, 8.0, 9.0], "Nota matematica": [8.0, 10.0, 7.0, 6.0, np.nan]}, index=['a', 'b', 'c', 'd', 'e'])

print(df_ex4)

   Nota romana  Nota matematica
a         10.0              8.0
b          8.0             10.0
c          NaN              7.0
d          8.0              6.0
e          9.0              NaN


+ Afisati toate notele la romana.

In [0]:
df_ex4.iloc[0:5,0] 

a    10.0
b     8.0
c     NaN
d     8.0
e     9.0
Name: Nota romana, dtype: float64

+ Afisati elementele de pe linia 'b'

In [0]:
df_ex4.loc['b','Nota romana':'Nota matematica'] 

Nota romana         8.0
Nota matematica    10.0
Name: b, dtype: float64

+ Scrieti mai multe instructiunile care vor genera toate notele de 8 

    - accesand coloanele
    - accesand liniile (loc si cu iloc)
    - cu **df[df==8]**

In [0]:
print(df_ex4)

print('\n')

print(df_ex4[df_ex4 == 8])

print('\n')

print(df_ex4.iloc[[1, 3], [0, 1]])

print('\n')

print(df_ex4.loc[['b', 'd'], ['Nota romana', 'Nota matematica']])

   Nota romana  Nota matematica
a         10.0              8.0
b          8.0             10.0
c          NaN              7.0
d          8.0              6.0
e          9.0              NaN


   Nota romana  Nota matematica
a          NaN              8.0
b          8.0              NaN
c          NaN              NaN
d          8.0              NaN
e          NaN              NaN


   Nota romana  Nota matematica
b          8.0             10.0
d          8.0              6.0


   Nota romana  Nota matematica
b          8.0             10.0
d          8.0              6.0


---

Putem adauga o coloana noua.

In [0]:
t2

,x,y,z,t
unu,6,2,0,8
doi,6,-3,2,3
trei,6,7,-8,13


In [0]:
t2['p'] = pd.Series([2, 4, 5], index = ['unu', 'doi', 'trei'])
t2

,x,y,z,t,p
unu,6,2,0,8,2
doi,6,-3,2,3,4
trei,6,7,-8,13,5


Putem sterge o coloana.

In [0]:
del t2['x']
t2

,y,z,t,p
unu,2,0,8,2
doi,-3,2,3,4
trei,7,-8,13,5


In [0]:
t2.values

array([[ 2,  0,  8,  2],
       [-3,  2,  3,  4],
       [ 7, -8, 13,  5]])

In [0]:
t2.index

Index(['unu', 'doi', 'trei'], dtype='object')

In [0]:
t2

,y,z,t,p
unu,2,0,8,2
doi,-3,2,3,4
trei,7,-8,13,5


Putem sterge o coloana cu functia drop (va crea o noua DataFrame fara coloana respectiva). Nu modifica dataFrame-ul cum o face functia del.

In [0]:
t2.drop(columns={'t'})

,y,z,p
unu,2,0,2
doi,-3,2,4
trei,7,-8,5


In [0]:
t2

,y,z,t,p
unu,2,0,8,2
doi,-3,2,3,4
trei,7,-8,13,5


In [0]:
print(t2.drop(columns=['y','t']))
t2

,y,z,t,p
unu,2,0,8,2
doi,-3,2,3,4
trei,7,-8,13,5


In [0]:
t2 = t2.drop(columns={'t'}) # daca vrem ca sa t2 sa se schimbe in urma aplicarii functiei drop
t2

,y,z,p
unu,2,0,2
doi,-3,2,4
trei,7,-8,5


Putem sterge si linii. Folosim parametrul axis = 1

In [0]:
df_4

,Temp_noaptea
0,3.0
1,NaN
2,8.0
3,12.0


In [0]:
df_4 = df_4.drop(axis =1, index = range(2,4)) # axis 0 - columns, axis 1 - rows

In [0]:
df_4

,Temp_noaptea
0,3.0
1,NaN


---

## Ex.5.

+ In dataFrame-ul creat la ex. 4, inserati coloana 'Nota fizica' cu valorile [6, 8, 7, 10, 9]

In [0]:
df_ex4['Nota fizica'] = [6,8,7,10,9]

df_ex4

,Nota romana,Nota matematica,Nota fizica
a,10.0,8.0,6
b,8.0,10.0,8
c,NaN,7.0,7
d,8.0,6.0,10
e,9.0,NaN,9


+ Creati o copie a tabelulul fara coloana 'Nota romana'.

In [0]:
df_ex4_copie = df_ex4.drop(columns=['Nota romana'])
df_ex4_copie

,Nota matematica,Nota fizica
a,8.0,6
b,10.0,8
c,7.0,7
d,6.0,10
e,NaN,9


+ Scrieti instructiunile pentru a sterge complet coloana 'Nota romana'.

In [0]:
df_ex4 = df_ex4.drop(columns=['Nota romana']) 
df_ex4

,Nota matematica,Nota fizica
a,8.0,6
b,10.0,8
c,7.0,7
d,6.0,10
e,NaN,9


+ Creati o copie a DF fara liniile a si e

In [0]:
df_ex4_copie = df_ex4.drop(axis=1,index=['a','e'])
df_ex4_copie

,Nota matematica,Nota fizica
b,10.0,8
c,7.0,7
d,6.0,10
