In [0]:
import numpy as np
print(np.__version__)

1.23.5


In [0]:
a = np.array([1, 2, 3, 4])

In [0]:
a

array([1, 2, 3, 4])

In [0]:
a.dtype

dtype('int64')

In [0]:
a.astype(np.float64)

array([1., 2., 3., 4.])

In [0]:
a

array([1, 2, 3, 4])

In [0]:
a = a.astype(np.float64)


In [0]:
a

array([1., 2., 3., 4.])

In [0]:
a.dtype

dtype('float64')

In [0]:
b = np.array([1.5, 2.5, 3.5, 4.5])
b

array([1.5, 2.5, 3.5, 4.5])

In [0]:
b = b.astype(np.int64)

In [0]:
b

array([1, 2, 3, 4])

In [0]:
b = b.astype(str)

In [0]:
b[0] = 'a'

In [0]:
b

array(['a', '2', '3', '4'], dtype='<U21')

In [0]:
b.astype(int)

array([1, 2, 3, 4])

In [0]:
a = np.array([[1, 2],[3, 4], [5, 6], [7, 8]])
a

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [0]:
b  = np.array([[1, -2],[-3, 7], [3, 6], [7, 5]])
b

array([[ 1, -2],
       [-3,  7],
       [ 3,  6],
       [ 7,  5]])

In [0]:
t = (a== b)
t

array([[ True, False],
       [False, False],
       [False,  True],
       [ True, False]])

In [0]:
a.sum()

36

In [0]:
(a==b).sum()

3

In [0]:
t.sum()

3

In [0]:
(a!=b).sum()

5

In [0]:
(a==a).sum()

8

In [0]:
(a!=a).sum()

0

In [0]:
b

array([[ 1, -2],
       [-3,  7],
       [ 3,  6],
       [ 7,  5]])

In [0]:
(b>1).sum()

5

In [0]:
(b >0).sum()

6

In [0]:
(b<=0).sum()

2

In [0]:
np.cos(a)

array([[ 0.54030231, -0.41614684],
       [-0.9899925 , -0.65364362],
       [ 0.28366219,  0.96017029],
       [ 0.75390225, -0.14550003]])

In [0]:
b = np.abs(b)

In [0]:
b

array([[1, 2],
       [3, 7],
       [3, 6],
       [7, 5]])

In [0]:
np.sum(b)

34

In [0]:
np.mean(b)

4.25

In [0]:
np.std(b)

2.165063509461097

In [0]:
b.mean()

4.25

In [0]:
 a

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [0]:
a.sum(axis=1)

array([ 3,  7, 11, 15])

In [0]:
a[0]

array([1, 2])

In [0]:
a

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [0]:
a[1]

array([3, 4])

In [0]:
a[1, 1]

4

In [0]:
a[:, 0]

array([1, 3, 5, 7])

In [0]:
a

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [0]:
a[:, 1]

array([2, 4, 6, 8])

In [0]:
a[:2, 0]

array([1, 3])

In [0]:
a.max()

8

In [0]:
a.argmax()

7

In [0]:
a[3,0] = 9

In [0]:
a

array([[1, 2],
       [3, 4],
       [5, 6],
       [9, 8]])

In [0]:
a.max()

9

In [0]:
a.argmax()

6

In [0]:
a[3,1] =9

In [0]:
a

array([[1, 2],
       [3, 4],
       [5, 6],
       [9, 9]])

In [0]:
(a>0).any()

True

In [0]:
a>0

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

In [0]:
(a==b).any?

Signature: any(iterable, /)
Docstring:
Return True if bool(x) is True for any x in the iterable.

If the iterable is empty, return False.
Type:      builtin_function_or_method

In [0]:
a

array([[1, 2],
       [3, 4],
       [5, 6],
       [9, 9]])

In [0]:
a.all()

True