# Exercitii_2 Numpy

Import librarie

In [0]:
import numpy as np

+ Ex. 1

Creati un ndarray cu valorile 0,2,4,...., 100

In [0]:
a = np.arange(0,102,2)

print(a)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


+ Ex. 2

Creati un ndarray cu 4x5 cu toate elementele egale cu 6.

In [0]:
b = np.full((4,5),6)

print(b)

[[6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]]


+ Ex. 3

Creati un ndarray si calculati media si suma elementelor si afisati folosind print

In [0]:
c = [3, 5, 7, 2]

suma = np.sum(c)
media = np.mean(c)

print(suma)
print(media)

17
4.25


+ Ex. 4

Creati un ndarray cu elemente de tip string. Scrieti un cod care afiseaza elementele o singura data, in ordine lexicografica cate unul pe linie.

In [0]:
tipuri = np.array(['Masini', 'Scari', 'Fructe', 'Cuie'])
unice = np.unique(tipuri)

print(unice)

['Cuie' 'Fructe' 'Masini' 'Scari']


+ Ex. 5

Scrieti o functie care primeste ca argument un ndarray si returneaza true daca acesta contine cel putin un numar intre 11-15 

In [0]:
def verificareRange(vector):
    return np.any(vector>=11) & np.any(vector<=15)

numere = np.array([4, 23, 11, 13, 0])

Testati functia pentru cel putin doi vectori

In [0]:
print(verificareRange(numere))
print(verificareRange(np.array([1,2])))
print(verificareRange(np.array([14])))

True
False
True


+ Ex. 6

Generati un ndarray cu 25 de elem intregi in intervalul 0-99 generate aleator

In [0]:
np.random.randint(0, 101, 25)

array([ 78,  37,  83,   9,   7,  28,  92,  10,  15,  21,  77,  47,  30,
        17,  10,  57,  73,  59,  71,  32,  56,  23,  35,  38, 100])

Sa se scrie un cod folosind functia where ce genereaza un ndarray cu elemente lui w modificate astfel: \
elementele intre valorile 20 si 50 sa fie trecute cu semnul -

In [0]:
w = np.array([3, 0, 7, 21, 20, 17, 35, 44, 89])

In [0]:
w_negativ = np.where((w>=20) & (w<=50), -w, w) # ultimul arg. reprezinta elementele ce nu indeplinesc verificarea

[  3   0   7 -21 -20  17 -35 -44  89]


In [0]:
print(w_negativ)

[  3   0   7 -21 -20  17 -35 -44  89]
